import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Sparkles, Copy, Check, FileText } from 'lucide-react';
import { useState } from 'react';

interface ExecutiveSummaryProps {
    summary: string;
    loading: boolean;
}

const ExecutiveSummary = ({ summary, loading }: ExecutiveSummaryProps) => {
    const [copied, setCopied] = useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(summary);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    if (loading) {
        return (
            <div className="bg-white/5 backdrop-blur-md rounded-xl p-6 border border-white/10 animate-pulse">
                <div className="flex items-center gap-2 mb-4">
                    <div className="w-5 h-5 bg-white/20 rounded-full"></div>
                    <div className="h-6 w-48 bg-white/20 rounded"></div>
                </div>
                <div className="space-y-3">
                    <div className="h-4 bg-white/10 rounded w-full"></div>
                    <div className="h-4 bg-white/10 rounded w-5/6"></div>
                    <div className="h-4 bg-white/10 rounded w-4/6"></div>
                </div>
            </div>
        );
    }

    if (!summary) return null;

    return (
        <div className="bg-white/5 backdrop-blur-md rounded-xl p-6 mb-6 border border-white/10 shadow-xl overflow-hidden relative group">
            <div className="absolute top-0 right-0 p-4 opacity-0 group-hover:opacity-100 transition-opacity">
                <button
                    onClick={handleCopy}
                    className="p-2 hover:bg-white/10 rounded-lg text-white/50 hover:text-white transition-colors"
                    title="Copy Analysis"
                >
                    {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
                </button>
            </div>

            <div className="flex items-center gap-2 mb-6 text-blue-300 border-b border-white/5 pb-4">
                <Sparkles className="w-5 h-5" />
                <h2 className="text-lg font-bold tracking-wide">AI Executive Analysis</h2>
            </div>

            <div className="prose prose-invert prose-sm max-w-none text-white/80">
                <ReactMarkdown
                    remarkPlugins={[remarkGfm]}
                    components={{
                        h1: ({ node, ...props }) => <h3 className="text-xl font-bold text-white mt-6 mb-3 border-l-4 border-blue-500 pl-3" {...props} />,
                        h2: ({ node, ...props }) => <h4 className="text-lg font-semibold text-blue-200 mt-5 mb-2 flex items-center gap-2" {...props} />,
                        h3: ({ node, ...props }) => <h5 className="text-md font-medium text-white/90 mt-4 mb-2 uppercase tracking-wider text-xs" {...props} />,
                        ul: ({ node, ...props }) => <ul className="space-y-1 my-3 list-disc list-outside ml-4 marker:text-blue-500/50" {...props} />,
                        ol: ({ node, ...props }) => <ol className="space-y-1 my-3 list-decimal list-outside ml-4 marker:text-blue-500/50" {...props} />,
                        li: ({ node, ...props }) => <li className="text-white/80 leading-relaxed" {...props} />,
                        blockquote: ({ node, ...props }) => <blockquote className="border-l-2 border-yellow-500/50 pl-4 py-1 my-4 bg-yellow-500/5 rounded-r italic text-yellow-100/80" {...props} />,
                        table: ({ node, ...props }) => <div className="overflow-x-auto my-6 rounded-lg border border-white/10"><table className="w-full text-left border-collapse" {...props} /></div>,
                        thead: ({ node, ...props }) => <thead className="bg-white/10 text-white uppercase text-xs" {...props} />,
                        th: ({ node, ...props }) => <th className="px-4 py-3 font-semibold border-b border-white/10" {...props} />,
                        td: ({ node, ...props }) => <td className="px-4 py-3 border-b border-white/5 text-xs text-white/70" {...props} />,
                        strong: ({ node, ...props }) => <strong className="text-white font-bold bg-white/5 px-1 rounded" {...props} />,
                        code: ({ node, ...props }) => <code className="bg-black/30 px-1.5 py-0.5 rounded text-xs font-mono text-blue-300" {...props} />,
                    }}
                >
                    {summary}
                </ReactMarkdown>
            </div>

            <div className="mt-8 pt-4 border-t border-white/5 flex gap-2 items-center text-[10px] text-white/30">
                <FileText className="w-3 h-3" />
                Generated by Mistral AI • Score-Aware Analysis
            </div>
        </div>
    );
};

export default ExecutiveSummary;
